#!/usr/bin/env bash
# Delete merged branches on origin (GitHub).
# Run this from your local clone with normal GitHub credentials.
#
# Categories:
#   38 claude/* — auto-generated by Claude Code, all squash-merged
#   5  sync/issue-* — auto-generated by issue lifecycle workflow
#
# The script ASKS before touching feat/*, fix/*, prod — those may
# carry unmerged production work.

set -e

echo "=== Phase 1: claude/* branches (38) ==="
for branch in \
  claude/add-phase-3a-test-cases-E5QDY \
  claude/admiring-shaw-5fe930 \
  claude/angry-hamilton-7170f8 \
  claude/blissful-chatterjee-ef85e6 \
  claude/cash-wizard-subtypes-mu8w3 \
  claude/check-phase-issues-status-Zd3tz \
  claude/clever-archimedes \
  claude/complete-p3a-9-tests-00zsd \
  claude/continue-refactoring-V5reF \
  claude/cool-raman-93c3f4 \
  claude/fervent-meitner-c1d8a5 \
  claude/filter-telegram-test-cases-MJiwB \
  claude/fix-auto-sync-docs-AQzCQ \
  claude/fix-finance-assistant-errors-jz3dj \
  claude/fix-github-automation-lyZYg \
  claude/fix-issue-17-status-Ncll9 \
  claude/fix-issue-sync-flow-TxavH \
  claude/fix-issues-sync-2SqiT \
  claude/implement-epic-1-phase-3.5-dkYqv \
  claude/implement-epic-2-p3a-GgkPL \
  claude/implement-epic-3-phase-3a-3aCsL \
  claude/implement-epic-4-p3a-T9Vxe \
  claude/implement-issue-14-TH4FO \
  claude/implement-issues-26-27-4VB2I \
  claude/implement-phase-3a-epic-1-cQMui \
  claude/implement-step-1-UjSPJ \
  claude/keen-diffie-2a2599 \
  claude/kind-shtern-d5f5d9 \
  claude/laughing-kapitsa-3a81de \
  claude/nostalgic-tesla-f70ae3 \
  claude/optimistic-wescoff-23aa66 \
  claude/organize-docs-structure-nZNXL \
  claude/phase-2-implementation-FTL33 \
  claude/phase-2-implementation-JqFFU \
  claude/phase-3a-test-cases-MMpL0 \
  claude/review-refactor-docs-uiWaC \
  claude/romantic-nightingale-3aadc1 \
  claude/stupefied-goldstine-b73b65; do
  echo "  deleting $branch ..."
  git push origin --delete "$branch" 2>&1 | grep -v "^$" || true
done

echo ""
echo "=== Phase 2: sync/issue-* branches (5) ==="
for branch in \
  sync/issue-7 \
  sync/issue-11 \
  sync/issue-14 \
  sync/issue-17 \
  sync/issue-19; do
  echo "  deleting $branch ..."
  git push origin --delete "$branch" 2>&1 | grep -v "^$" || true
done

echo ""
echo "=== Phase 3: feat/* and fix/* — REVIEW BEFORE DELETING ==="
echo "These might carry unmerged production work:"
echo "  feat/bot-text-handler-user-registration-miniapp-fixes"
echo "    (top: e3cabb6 chore: cloudflare tunnel scripts + gitignore + expense_cli cleanup)"
echo "  fix/settings-extra-ignore"
echo "    (top: ea761d8 fix(config): allow extra env vars so POSTGRES_* keys don't break startup)"
echo ""
echo "The fix/settings-extra-ignore content IS already in main (verified)."
echo "The feat/* branch has stale content — likely superseded by later PRs."
echo ""
echo "If you want to delete them too, run:"
echo "  git push origin --delete feat/bot-text-handler-user-registration-miniapp-fixes"
echo "  git push origin --delete fix/settings-extra-ignore"
echo ""
echo "=== KEEP ==="
echo "  main  — primary integration branch (KEEP)"
echo "  prod  — production deployment branch (KEEP unless you confirm otherwise)"
echo ""
echo "Done."
